openapi: 3.1.0
info:
  title: Todo API
  description: API for managing Todo items
  version: 1.0.0
paths:
  /api/todo:
    post:
      summary: Create a new Todo
      description: Creates a new Todo with default values
      operationId: createTodo
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                required:
                  - id
  /api/todo/{id}:
    get:
      summary: Get a Todo by ID
      description: Retrieves a Todo item by its ID
      operationId: getTodoById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the Todo to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Todo retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  title:
                    type: string
                  description:
                    type: string
                required:
                  - id
                  - title
                  - description
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
        '400':
          description: Invalid UUID format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
