name: Swift Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/swift-test.yaml"
      - "**.swift"
      - "Package.resolved"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  small:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: swift-build-package-resolved-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('Package.resolved') }}
          path: .build
      - run: swift build
      - run: swift test
        env:
          SMALL: true