name: Swift format
on:
  pull_request:
    paths:
      - ".github/workflows/swift-format.yaml"
      - "**.swift"
      - ".swift-format"
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 5
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install swift-format
      - run: swift format lint -s --configuration .swift-format -r Sources Tests Package.swift